In [1]:
#建立list
a = [1, 3, 5, 7, 9]
a * 2

b = [2, 4, 6, 8 ,10]
a + b

result = []
for i in range(5):
    result.append(a[i] + b[i])

result

[3, 7, 11, 15, 19]

In [2]:
import numpy as np

#透過list建立ndArray

a_array = np.array([1, 3, 5, 7, 9])
a_array * 2

b_array = np.array([2, 4, 6, 8 ,10])

a_array + b_array

array([ 3,  7, 11, 15, 19])

In [3]:
#使用python建立5個亂數元素的list
import random

#list comprehension
[random.randint(50,100) for _ in range(5)]

[87, 96, 83, 99, 56]

In [4]:
#使用numpy random 建立亂數
import numpy as np
np.random.randint(50,high=100,size=5)

array([92, 62, 64, 58, 77])

In [5]:
np.random.randint(50,high=100,size=(50, 5))

array([[58, 69, 87, 53, 53],
       [61, 50, 81, 68, 76],
       [78, 54, 52, 71, 61],
       [95, 66, 60, 64, 62],
       [90, 63, 91, 91, 71],
       [99, 68, 58, 52, 50],
       [80, 55, 89, 91, 85],
       [76, 64, 63, 80, 85],
       [94, 68, 71, 89, 68],
       [69, 59, 77, 98, 60],
       [74, 53, 82, 50, 74],
       [69, 75, 62, 57, 61],
       [95, 94, 50, 56, 75],
       [53, 87, 62, 92, 62],
       [63, 71, 50, 97, 63],
       [78, 60, 58, 81, 80],
       [59, 81, 77, 62, 90],
       [54, 94, 65, 90, 69],
       [96, 72, 86, 82, 54],
       [73, 65, 55, 71, 67],
       [87, 79, 91, 68, 69],
       [56, 76, 59, 52, 63],
       [91, 78, 70, 74, 71],
       [83, 86, 70, 70, 58],
       [95, 64, 88, 56, 58],
       [93, 78, 59, 88, 53],
       [81, 73, 60, 69, 54],
       [89, 57, 64, 69, 56],
       [69, 79, 96, 61, 51],
       [53, 95, 95, 93, 56],
       [69, 61, 55, 93, 53],
       [85, 61, 79, 92, 79],
       [67, 80, 55, 74, 79],
       [50, 67, 60, 60, 65],
       [79, 90