In [1]:
#使用list建立Series
import pandas as pd

s1 = pd.Series([4, 7, -5, 3])
s1

0    4
1    7
2   -5
3    3
dtype: int64

In [2]:
#使用index, values
s1.index

RangeIndex(start=0, stop=4, step=1)

In [3]:
s1.values

array([ 4,  7, -5,  3])

In [4]:
#自訂Serires的index

s2 = pd.Series([4, 7, -5, 3],index=['d', 'b', 'a', 'c'])
s2

d    4
b    7
a   -5
c    3
dtype: int64

In [5]:
s2.index

Index(['d', 'b', 'a', 'c'], dtype='object')

In [6]:
s2.values

array([ 4,  7, -5,  3])

In [8]:
s2.values

array([ 4,  7, -5,  3])

In [9]:
display(s2)
print("===========")
display(s2['a'])
s2['a'] = 5
print("===========")
display(s2)
print("============")
s2[["c", "b", "d"]]

d    4
b    7
a   -5
c    3
dtype: int64

-5

d    4
b    7
a    5
c    3
dtype: int64

c    3
b    7
d    4
dtype: int64

In [10]:
import numpy as np
display(s2)
print("==========")
display(s2 * 2)
np.exp(s2)

d    4
b    7
a    5
c    3
dtype: int64

d     8
b    14
a    10
c     6
dtype: int64

d      54.598150
b    1096.633158
a     148.413159
c      20.085537
dtype: float64

In [11]:
'e' in s2, 'a' in s2

(False, True)